language: c++
dist: trusty
sudo: true
notifications:
  email: false

# notes:
# python, zlib, and clang 3.9 are already available.

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - sourceline: 'ppa:adrozdoff/cmake'
        packages:
          - cmake
          - cmake-data
          - ninja-build
    env:
      - MATRIX_EVAL="CC=clang && CXX=clang++"
    
# run cmake
before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir build install
  - pushd build
  - cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug -DLLVM_PARALLEL_LINK_JOBS=2 -DLLVM_TARGETS_TO_BUILD="X86" ..
    
# part 1 of building, just build LLC
install:
  - ninja llc -j4

# part 2 of building + run x86 codegen tests.
script:
  - ninja check-llvm-codegen-x86 -j4
