language: c++
dist: trusty
sudo: required
notifications:
  email: false

# notes:
# - it is very difficult to stay within travis-ci.ORG time limit (50m), currently
#   this runs reliably on travis-ci.COM (120m).
#
# - While sudo is not technically "required", we claim that it is so that Travis spins up
#   a full virtual machine. We can't use Travis's Docker instances because of its disk 
#   space limitations.

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - sourceline: 'ppa:adrozdoff/cmake'
        packages:
          - cmake
          - cmake-data
          - ninja-build
          - binutils-gold
    env:
      - MATRIX_EVAL="CC=clang && CXX=clang++"
    
# run cmake
before_script:
  - eval "${MATRIX_EVAL}"
  - mkdir build install
  - pushd build
  - cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_LIT_ARGS="-sv --no-progress-bar" -DLLVM_PARALLEL_LINK_JOBS=2 -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_INCLUDE_EXAMPLES=Off -DLLVM_USE_LINKER=gold ..
    
# build assets
script:
  - ninja check-llvm-codegen-x86 -j4
  
