language: c++
dist: trusty
sudo: true
notifications:
  email: false

# notes:
# python, zlib, and clang 3.9 are already available.

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - sourceline: 'ppa:adrozdoff/cmake'
        packages:
          - cmake
          - cmake-data
          - ninja-build
    env:
      - MATRIX_EVAL="CC=clang && CXX=clang++"
    
before_install:
  - eval "${MATRIX_EVAL}"
    
install:
  - mkdir build install
  - pushd build
  - cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug ..
  - ninja check-llvm
