language: c++
dist: trusty
sudo: true

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:adrozdoff/cmake'
        packages:
        - clang-4.0
        - cmake
        - python
        - zlib1g-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    
before_install:
    - eval "${MATRIX_EVAL}"
    
install:
    mkdir build install
    pushd build
    cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug -DLLVM_ENABLE_WERROR ..
    make check-llvm -j3
