language: c++
dist: trusty
sudo: true

# notes for speeding this up:
# python, zlib, and clang 3.9 are already available.

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-4.0
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:adrozdoff/cmake'
        packages:
        #   - clang-4.0
          - cmake
        #   - python
        #   - zlib1g-dev
        #   - ninja
    env:
      - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    
before_install:
  - eval "${MATRIX_EVAL}"
    
install:
  - mkdir build install
  - pushd build
  - cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug ..
  - make check-llvm -j3
